"""Make ISBN and publisher in books nullable

Revision ID: 4dc6ea6937d7
Revises: a8cc336466b9
Create Date: 2025-08-23 15:26:51.853671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc6ea6937d7'
down_revision: Union[str, Sequence[str], None] = 'a8cc336466b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'ISBN',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'ISBN',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
