"""Add server-side timestamp defaults to posts, comments, and profiles

Revision ID: e528a6db0a65
Revises: 4dc6ea6937d7
Create Date: 2025-08-24 08:13:01.287458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e528a6db0a65'
down_revision: Union[str, Sequence[str], None] = '4dc6ea6937d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- 이 부분을 직접 추가합니다 ---
    op.alter_column('comment', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('comment', 'modify_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    # --- 여기까지 ---

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- 이 부분을 직접 추가합니다 ---
    op.alter_column('comment', 'modify_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               nullable=False,
               server_default=None)
    op.alter_column('comment', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               nullable=False,
               server_default=None)
    # --- 여기까지 ---
    
    # ### end Alembic commands ###